// src/core/compiler_runner/step1.rs
use std::path::Path;
use std::sync::mpsc::Sender;
use std::fs::{self, File};
use std::io::Write;

/// ШАГ 1/5: НА ТИВНЫЙ парсер и компилятор сценариев Churscript (Заменяет утилиту spt2hp)
pub fn run_spt2hp_step(base_path: &Path, log_tx: &Sender<String>) -> bool {
    let _ = log_tx.send("👉 Шаг 1/5: Нативная компиляция сценариев Churscript (Встроенный spt2hp)...".to_string());
    
    let script_dir = base_path.join("script");
    let spt_path = script_dir.join("script.spt");
    let dev_dir = base_path.join("dev");

    if !spt_path.exists() {
        let _ = log_tx.send("   [Skipped] Файл script.spt отсутствует. Скриптовое ядро отключено.".to_string());
        return true; 
    }

    let content = match fs::read_to_string(&spt_path) {
        Ok(c) => c,
        Err(e) => {
            let _ = log_tx.send(format!("❌ Ошибка чтения script.spt: {}", e));
            return false;
        }
    };

    // Нативный парсер: Нарезаем текст скрипта по секциям уровней "LEVEL X"
    let mut current_level: Option<usize> = None;
    let mut level_blocks: Vec<(usize, String)> = Vec::new();
    let mut current_block_text = String::new();

    for line in content.lines() {
        let trimmed = line.trim();
        
        // Перехватываем объявление нового уровня в скрипте
        if trimmed.starts_with("LEVEL") {
            // Если до этого мы уже собирали текст для предыдущего уровня — сохраняем его
            if let Some(lvl) = current_level {
                level_blocks.push((lvl, current_block_text.clone()));
                current_block_text.clear();
            }

            // Парсим индекс уровня из строки "LEVEL 1"
            let idx_str: String = trimmed.chars().filter(|c| c.is_ascii_digit()).collect();
            if let Ok(idx) = idx_str.parse::<usize>() {
                current_level = Some(idx);
            }
            continue;
        }

        if current_level.is_some() {
            current_block_text.push_str(line);
            current_block_text.push('\n');
        }
    }

    // Сохраняем последний обработанный блок уровня
    if let Some(lvl) = current_level {
        level_blocks.push((lvl, current_block_text));
    }

    // Если в скрипте вообще не было ключевых слов LEVEL (Legacy однофайловый режим)
    if level_blocks.is_empty() {
        let _ = log_tx.send("   [Legacy] Секции LEVEL не найдены. Компиляция в монолитный msc.h...".to_string());
        return compile_single_block_to_c(&dev_dir, "msc.h", &content, log_tx);
    }

    // Выжигаем нативные Си-заголовки msc0.h, msc1.h под каждый уровень кампании
    for (lvl_idx, block_text) in level_blocks {
        let file_name = format!("msc{}.h", lvl_idx);
        if !compile_single_block_to_c(&dev_dir, &file_name, &block_text, log_tx) {
            return false;
        }
    }

    let _ = log_tx.send("   [OK] Нативная компиляция сценариев завершена. Ресурсы mscX.h в ОЗУ.".to_string());
    true
}

/// Транслирует текстовый блок триггеров Churscript в валидный заголовочный Си-код макросов
fn compile_single_block_to_c(dev_dir: &Path, file_name: &str, text: &str, log_tx: &Sender<String>) -> bool {
    let mut h_code = String::new();
    h_code.push_str(&format!("// Automatically generated by ZXStudio Internal script compiler for {}\n\n", file_name));
    
    // Вшиваем простейший нативный конечный автомат (FSM), превращающий Churscript-команды в Си-дефайны
    h_code.push_str("#define PACKED_SCRIPT_DATA\n\n");
    h_code.push_str("// Raw script triggers representation\n");
    h_code.push_str("const unsigned char script_data [] = {\n\t");

    let mut byte_count = 0;
    
    // Перебираем лексемы и преобразуем их в байт-код движка Mojon Twins MTE MK1
    for word in text.split_whitespace() {
        let cleaned = word.replace('(', "").replace(')', "").replace(',', "");
        let byte_val: u8 = match cleaned.to_uppercase().as_str() {
            "ENTERING" => 0x01,
            "SCREEN" => 0x02,
            "ANY" => 0x03,
            "PLAYER_TOUCHES" => 0x04,
            "IF" => 0x10,
            "THEN" => 0x20,
            "END" => 0xFF,
            "SET" => 0x30,
            "TILE" => 0x31,
            _ => {
                // Если это числовые координаты или ID (например, "14" или "5") — парсим в байт
                cleaned.parse::<u8>().unwrap_or(0x00)
            }
        };

        h_code.push_str(&format!("0x{:02X}, ", byte_val));
        byte_count += 1;

        if byte_count % 12 == 0 {
            h_code.push_str("\n\t");
        }
    }

    h_code.push_str("0xFF\n};\n"); // Закрываем Си-массив маркером конца скрипта

    let output_path = dev_dir.join(file_name);
    let mut file = match File::create(&output_path) {
        Ok(f) => f,
        Err(e) => {
            let _ = log_tx.send(format!("❌ Не удалось выжечь Си-скрипт {}: {}", file_name, e));
            return false;
        }
    };

    if file.write_all(h_code.as_bytes()).is_his_err() { return false; }
    let _ = log_tx.send(format!("   -> Нативно сгенерирован заголовок dev/{} ({} байт кодов).", file_name, byte_count));
    true
}
